name: rider_flutter
description: Ride-sharing
publish_to: "none"

version: 3.1.2+233

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.1

  # Geo
  latlong2: ^0.9.0
  geolocator: ^10.1.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # State management
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.3

  # Dependency injection
  get_it: ^7.6.6
  injectable: ^2.3.2

  # Routing
  auto_route: ^7.8.4

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.1.0

  # Helpers
  dartz: ^0.10.1
  rxdart: ^0.27.7
  equatable: ^2.0.3
  path_provider: ^2.1.2
  json_annotation: ^4.8.1
  url_launcher: ^6.2.3
  connectivity_plus: ^5.0.0
  file_picker: ^6.0.0

  # Firebase
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_messaging: ^14.7.10

  # UI
  percent_indicator: ^4.2.3
  ionicons: 0.2.2
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.64.0
  dotted_border: ^2.1.0
  generic_map:
    path: ../../libs/generic_map
  flutter_common:
    path: ../../libs/flutter_common
  lottie: ^3.0.0
  animated_splash_screen: ^1.3.0
  flutter_launcher_icons: ^0.13.1

  # Network
  graphql: ^5.2.0-beta.7
  cached_network_image: ^3.3.1
  collection: ^1.17.2
  dotted_line: ^3.2.2
  flutter_map: ^6.0.1
  share_plus: ^7.2.1

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  flutter_gen_runner: ^5.4.0
  flutter_gen: ^5.4.0
  flutter_lints: ^3.0.0
  injectable_generator: ^2.4.1
  build_verify: ^3.1.0
  graphql_codegen: 0.13.11
  freezed: ^2.4.6
  json_serializable: ^6.7.1

  flutter_test:
    sdk: flutter

dependency_overrides:
  analyzer: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/avatars/
    - assets/lottie/
    - assets/countries/



  fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/generalsansextralight.ttf
          weight: 200
        - asset: assets/fonts/generalsanslight.ttf
          weight: 300
        - asset: assets/fonts/generalsansregular.ttf
          weight: 400
        - asset: assets/fonts/generalsansmedium.ttf
          weight: 500
        - asset: assets/fonts/generalsanssemibold.ttf
          weight: 600
        - asset: assets/fonts/generalsansbold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/interthin.ttf
          weight: 100
        - asset: assets/fonts/interextralight.ttf
          weight: 200
        - asset: assets/fonts/interlight.ttf
          weight: 300
        - asset: assets/fonts/interregular.ttf
          weight: 400
        - asset: assets/fonts/intermedium.ttf
          weight: 500
        - asset: assets/fonts/intersemibold.ttf
          weight: 600
        - asset: assets/fonts/interbold.ttf
          weight: 700
        - asset: assets/fonts/interextrabold.ttf
          weight: 800
        - asset: assets/fonts/interblack.ttf
          weight: 900

flutter_gen:
  integrations:
    lottie: true
# flutter_intl:
#   enabled: false
#   class_name: S
#   main_locale: en
#   output_dir: lib/l10n
#   arb_dir: lib/l10n
#   template_arb_file: intl_en.arb
#   generate_for:
#     - lib/l10n/intl_en.arb
