// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgeF0Ip2l__qZ1RYvVUf32LCJ-dUmn3u0',
    appId: '1:400865280573:web:45d3cbaa7021e5d6f3a054',
    messagingSenderId: '400865280573',
    projectId: 'yocar-7f15f',
    authDomain: 'yocar-7f15f.firebaseapp.com',
    storageBucket: 'yocar-7f15f.appspot.com',
    measurementId: 'G-2YSK8M032D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtsC3-WoufOVmsHFwbgfDYGcu9q8GwO0o',
    appId: '1:400865280573:android:fb6a0cece683e127f3a054',
    messagingSenderId: '400865280573',
    projectId: 'yocar-7f15f',
    storageBucket: 'yocar-7f15f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4LYzPf5f5BVs5p_aSeHkJDNvcPhcvl5U',
    appId: '1:400865280573:ios:14abdc690b56a5eaf3a054',
    messagingSenderId: '400865280573',
    projectId: 'yocar-7f15f',
    storageBucket: 'yocar-7f15f.appspot.com',
    iosBundleId: 'com.ridy.yocar.rider',
  );
}
